### PR TITLE
Move to .NET 5

### PR DESCRIPTION
**Pull request by sitiom**
.NET Framework is also deprecated for a long time now, and .NET 5 brings about performance improvements.

### CODE REVIEW

**Comment by mdhiggins** [comment]
Reverted this for now, getting performance issues especially when trying to close and reset threads

Also any idea why this forces the release to have an external DLL file?

**Comment by sitiom** [comment]
> Also any idea why this forces the release to have an external DLL file?

I think that is by design. You can create a non-self-contained, single-file executable by doing this:

```powershell
dotnet publish -c Release -r win10-x64 -p:PublishSingleFile=true --no-self-contained
````

**Comment by mdhiggins** [comment]
I tried that and was getting a size of like 170mb. Is that what you're seeing?

**Comment by sitiom** [comment]
> I tried that and was getting a size of like 170mb. Is that what you're seeing?

Hmm, no. I think you did not include the `​--​no​-​self​-​contained` flag at the end as with the command above.

**Comment by mdhiggins** [comment]
Gotcha I'll take a look at that. 

Are you seeing a long period of unresponsive when trying to exit the app via the tool tray menu before the icons reset back to default?

**Comment by sitiom** [comment]
> Gotcha I'll take a look at that.
> 
> Are you seeing a long period of unresponsive when trying to exit the app via the tool tray menu before the icons reset back to default?

Checked, and yeah, it gets unresponsive for around 10 seconds before it exits.

https://github.com/mdhiggins/CenterTaskbar/blob/e96642c8270b942cc9c49d3d314c0540f22d028c/CenterTaskbar/Program.cs#L547-L552

Has something to do with this, although it wasn't unresponsive in .NET Framework.

**Comment by mdhiggins** [comment]
Alright I restored the changes and was able to find a fix

https://github.com/mdhiggins/CenterTaskbar/commit/a338141c20f28e7895159f9141bfbdcc445dd797

I changed the above area to `Automation.RemoveAllEventHandlers();` which seems to function the same but without the period of unresponsiveness

Also added a new workflow that automates the publishing process when new commits are made

https://github.com/mdhiggins/CenterTaskbar/actions/runs/858072723

Try that build and see if its working for you

**Comment by sitiom** [comment]
Great, It works fine.

**Pull request merged**
