### PR TITLE
Threaded is now Tasked

### PR DESCRIPTION
**Pull request by ghost**
I used ReSharper to implement some best practice recommendations. Then I implemented the Task pattern because modern recommendation is to never manually create Threads. The task handler decides how to run stuff on the threadpool. This should allow us to run our tasks in parallel. On a multi-monitor setup with many taskbars you should see all the icons moving together at the same time. Tasks also come with a CancellationToken feature made to handle the Thread.Abort situation gracefully. All tasks can cancel at the same time because they all share the token. This is more threadsafe than the boolean cancel flag I was using.

### CODE REVIEW

**Comment by mdhiggins** [comment]
Appreciate your contributions here. My experience with C# is limited so these changes have been very helpful and educational

**Comment by amynbe** [comment]
Hi, sorry to ask here, but is the issue tab disabled for this repo on purpose? I just wanted to ask whether it would be possible to programmatically disable the grouping of taskbar buttons, beyond what MS Windows proposes (they are still grouped even when you select "never" in taskbar properties, just not merged).
My ultimate goal is to reorder the taskbar windows in most recently used order.
Thanks.

**Comment by mdhiggins** [comment]
Not possible with this script. You can movie the taskbar group as a whole but cannot manipulate individual icons without causing explorer to glitch and reload the UI.

**Comment by ghost** [comment]
@amynbe brings a good question. Did @mdhiggins disable Issues on purpose?

https://help.github.com/en/github/managing-your-work-on-github/disabling-issues

**Comment by mdhiggins** [comment]
Fixed

**Pull request merged**
